include(AI/AI_bullet_tests.cmake)
include(AI/AI_enemy_tests.cmake)
include(AI/A_star_tests.cmake)
include(AABB_tests.cmake)
include(barrier_tests.cmake)
include(bullet_tests.cmake)
include(collision_tests.cmake)
include(enemy_tests.cmake)
include(entity_tests.cmake)
include(gun_tests.cmake)
include(player_tests.cmake)
include(rate_limit_tests.cmake)
# include(health_bar_tests.cmake)
# include(health_tests.cmake)
