include(AABB_tests.cmake)
include(barrier_tests.cmake)
include(bullet_tests.cmake)
include(collision_tests.cmake)
# include(entity_tests.cmake)
# include(gun_tests.cmake)
# include(health_bar_tests.cmake)
# include(health_tests.cmake)
# include(player_tests.cmake)
